### ISSUE TITLE
Failed when using with webpack ^3.4.1

### ISSUE THREAD

**Issue by ryaa** [rensbaardman/rewire-webpack-plugin#22]
The error is as below

`running better-npm-run in /Users/alexryltsov/Git/BOSS811/fix-map-view-stuck
Executing script: test-watch

to be executed: karma start --auto-watch --no-single-run
TypeError: Cannot read property 'compilation' of undefined
    at RewireWebpackPlugin.apply (/Users/alexryltsov/Git/BOSS811/fix-map-view-stuck/node_modules/rewire-webpack-plugin/lib/RewireWebpackPlugin.js:14:18)
    at Compiler.apply (/Users/alexryltsov/Git/BOSS811/fix-map-view-stuck/node_modules/tapable/lib/Tapable.js:375:16)
    at webpack (/Users/alexryltsov/Git/BOSS811/fix-map-view-stuck/node_modules/webpack/lib/webpack.js:33:19)
    at Plugin (/Users/alexryltsov/Git/BOSS811/fix-map-view-stuck/node_modules/karma-webpack/lib/karma-webpack.js:87:16)
    at invoke (/Users/alexryltsov/Git/BOSS811/fix-map-view-stuck/node_modules/di/lib/injector.js:75:15)
    at Array.instantiate (/Users/alexryltsov/Git/BOSS811/fix-map-view-stuck/node_modules/di/lib/injector.js:59:20)
    at get (/Users/alexryltsov/Git/BOSS811/fix-map-view-stuck/node_modules/di/lib/injector.js:48:43)
    at /Users/alexryltsov/Git/BOSS811/fix-map-view-stuck/node_modules/di/lib/injector.js:71:14
    at Array.map (<anonymous>)
    at Array.invoke (/Users/alexryltsov/Git/BOSS811/fix-map-view-stuck/node_modules/di/lib/injector.js:70:31)
    at Injector.get (/Users/alexryltsov/Git/BOSS811/fix-map-view-stuck/node_modules/di/lib/injector.js:48:43)
    at instantiatePreprocessor (/Users/alexryltsov/Git/BOSS811/fix-map-view-stuck/node_modules/karma/lib/preprocessor.js:55:20)
    at Array.forEach (<anonymous>)
    at createPreprocessor (/Users/alexryltsov/Git/BOSS811/fix-map-view-stuck/node_modules/karma/lib/preprocessor.js:74:20)
    at Array.invoke (/Users/alexryltsov/Git/BOSS811/fix-map-view-stuck/node_modules/di/lib/injector.js:75:15)
    at get (/Users/alexryltsov/Git/BOSS811/fix-map-view-stuck/node_modules/di/lib/injector.js:48:43)
17 03 2020 08:12:59.031:ERROR [preprocess]: Can not load "webpack"!
  TypeError: Cannot read property 'compilation' of undefined
    at RewireWebpackPlugin.apply (/Users/alexryltsov/Git/BOSS811/fix-map-view-stuck/node_modules/rewire-webpack-plugin/lib/RewireWebpackPlugin.js:14:18)
    at Compiler.apply (/Users/alexryltsov/Git/BOSS811/fix-map-view-stuck/node_modules/tapable/lib/Tapable.js:375:16)
    at webpack (/Users/alexryltsov/Git/BOSS811/fix-map-view-stuck/node_modules/webpack/lib/webpack.js:33:19)
    at Plugin (/Users/alexryltsov/Git/BOSS811/fix-map-view-stuck/node_modules/karma-webpack/lib/karma-webpack.js:87:16)
    at invoke (/Users/alexryltsov/Git/BOSS811/fix-map-view-stuck/node_modules/di/lib/injector.js:75:15)
    at Array.instantiate (/Users/alexryltsov/Git/BOSS811/fix-map-view-stuck/node_modules/di/lib/injector.js:59:20)
    at get (/Users/alexryltsov/Git/BOSS811/fix-map-view-stuck/node_modules/di/lib/injector.js:48:43)
    at /Users/alexryltsov/Git/BOSS811/fix-map-view-stuck/node_modules/di/lib/injector.js:71:14
    at Array.map (<anonymous>)
    at Array.invoke (/Users/alexryltsov/Git/BOSS811/fix-map-view-stuck/node_modules/di/lib/injector.js:70:31)
    at Injector.get (/Users/alexryltsov/Git/BOSS811/fix-map-view-stuck/node_modules/di/lib/injector.js:48:43)
    at instantiatePreprocessor (/Users/alexryltsov/Git/BOSS811/fix-map-view-stuck/node_modules/karma/lib/preprocessor.js:55:20)
    at Array.forEach (<anonymous>)
    at createPreprocessor (/Users/alexryltsov/Git/BOSS811/fix-map-view-stuck/node_modules/karma/lib/preprocessor.js:74:20)
    at Array.invoke (/Users/alexryltsov/Git/BOSS811/fix-map-view-stuck/node_modules/di/lib/injector.js:75:15)
    at get (/Users/alexryltsov/Git/BOSS811/fix-map-view-stuck/node_modules/di/lib/injector.js:48:43)`

**Comment by rensbaardman** [comment]
This version works only with Webpack 4. For version 3, try [rewire-webpack](https://github.com/jhnns/rewire-webpack) ([NPM](https://www.npmjs.com/package/rewire-webpack)).
